/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container": "#201f1f",
        "secondary-fixed": "#8ef4e9",
        "on-primary-container": "#f8f6ff",
        "on-tertiary-fixed": "#291800",
        "inverse-primary": "#4858ab",
        "on-tertiary-container": "#fff6ee",
        "on-surface-variant": "#c6c5d3",
        "on-surface": "#e5e2e1",
        "primary-fixed": "#dee0ff",
        "surface-container-lowest": "#0e0e0e",
        "inverse-surface": "#e5e2e1",
        "on-tertiary-fixed-variant": "#633f00",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#00504a",
        "surface-container-high": "#2a2a2a",
        "surface-tint": "#bac3ff",
        "background": "#131313",
        "surface-bright": "#393939",
        "outline-variant": "#454651",
        "on-secondary": "#003733",
        "primary-fixed-dim": "#bac3ff",
        "tertiary-fixed": "#ffddb4",
        "on-error-container": "#ffdad6",
        "surface-variant": "#353534",
        "secondary": "#71d7cd",
        "surface-container-highest": "#353534",
        "on-secondary-fixed": "#00201d",
        "tertiary": "#ffb954",
        "on-primary": "#15267b",
        "on-background": "#e5e2e1",
        "surface": "#131313",
        "primary-container": "#5c6bc0",
        "on-primary-fixed": "#00105b",
        "secondary-fixed-dim": "#71d7cd",
        "tertiary-container": "#9c6600",
        "inverse-on-surface": "#313030",
        "secondary-container": "#32a097",
        "outline": "#8f909d",
        "surface-container-low": "#1c1b1b",
        "on-tertiary": "#452b00",
        "error": "#ffb4ab",
        "on-secondary-container": "#00302c",
        "error-container": "#93000a",
        "primary": "#bac3ff",
        "tertiary-fixed-dim": "#ffb954",
        "surface-dim": "#131313",
        "on-primary-fixed-variant": "#2f3f92"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Inter"],
        "mono": ["JetBrains Mono"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem",
        "dashboard": "0.75rem"
      },
    },
  },
  plugins: [],
}
